- name: A playbook to start service and scale application
  hosts: localhost
  user: ubuntu
  become: yes
  
  tasks:
  - name: 1. Update APT Package Manager
    apt:
      update_cache: yes
      
  - name: 2. Create New Service
    command: kubectl expose deployment/server-app --type="NodePort" --port 8080 --name node-port-service  
