- name: A playbook to deploy a custom docker image to minikube
  hosts: localhost
  user: ubuntu
  become: yes
  
  tasks:
  - name: 1. Update APT Package Manager
    apt:
      update_cache: yes
  
  - name: 2. Deploy Image
    command: kubectl create deployment server-app --image=steveystyle/server_app:1.0
    become: no
