apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2022-01-01T02:57:41Z"
  generation: 1
  labels:
    app: server-app
  name: server-app
  namespace: default
  resourceVersion: "472"
  uid: 71b25d43-38c8-4ee0-a528-cc44636a24a5
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: server-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: server-app
    spec:
      containers:
      - image: docker.io/steveystyle/server-app:1.0
        imagePullPolicy: IfNotPresent
        name: server-app
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-01-01T02:58:20Z"
  labels:
    app: server-app
  name: node-port-service
  namespace: default
  resourceVersion: "521"
  uid: 20a20f3f-2d23-4d12-8038-d39f0aae541b
spec:
  clusterIP: 10.101.43.62
  clusterIPs:
  - 10.101.43.62
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31676
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: server-app
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
